export default {
  "Slightly smiling face": "🙂",
  "Smiling face": "☺",
  "Smiling face with big eyes": "😃",
  "Smiling face with smiling eyes": "😊",
  "Beaming face with smiling eyes": "😁",
  "Smiling face with tears": "🥲",
  "Grinning face": "😆",
  "Rolling on the floor laughing": "🤣",
  "Lauging with tears": "😂",
  "Upside down face": "🙃",
  "Winking face": "😉",
  "Smiling face with halo": "😇",
  "Smiling face with sunglasses": "😎",
  "Nerdy face": "🤓",
  "Face with monocle": "🧐",
  "Partying face": "🥳",
  "Smiling face with hearts": "🥰",
  "Smiling face with heart eyes": "😍",
  "Star-struck": "🤩",
  "Face blowing kiss": "😘",
  "Kissing face": "😗",
  "Kissing face with closed eyes": "😚",
  "Kissng face with smiling eyes": "😙",
  "Yummy face": "😋",
  "Face with tongue": "😛",
  "WInking face with tongue": "😜",
  "Zanny face": "🤪",
  "Squinting face with tongue": "😝",
  "Money face with money tongue": "🤑",
  Hugs: "🤗",
  "Face with hand in mouth": "🤭",
  "Shushing face": "🤫",
  "Thinkin face": "🤔",
  "Neutral face": "😐",
  "Zipped mouth": "🤐",
  "Face with raised eyebrow": "🤨",
  "Expressionless face": "😑",
  "Face with no mouth": "😶",
  "Smirking face": "😏",
  "Unamused face": "😒",
  "Face with rolling eyes": "🙄",
  "Grimacing face": "😮‍💨",
  "Lying face": "🤥",
  "Sleepy face": "😪",
  "Sleeping face": "😴",
  "Relieved face": "😌",
  "Pensive face": "😔",
  "Drooling face": "🤤",
  "Face with mask": "😷",
  "Face with thermometer": "🤒",
  "Face with bandage": "🤕",
  "Nauseous face": "🤢",
  "Vomiting face": "🤮",
  "Sneezing face": "🤧",
  "Hot face": "🥵",
  "Cold face": "🥶",
  "Woozy face": "🥴",
  "Face with crossed-out face": "😵",
  "Face with exploding head": "🤯",
  "Confused face": "😕",
  "Worried face": "😟",
  "Slightly frowning face": "🙁",
  "Frowning face": "☹",
  "Face with open mouth": "😮",
  "Hushed face": "😯",
  "Astonished face": "😲",
  "Flushed face": "😳",
  "Begging face": "🥺",
  "Frowning face with open mouth": "😦",
  "Angushed face": "😧",
  "Fearful face": "😨",
  "Anxious face with sweat": "😰",
  "Sad but relieved face": "😥",
  "Crying face": "😢",
  "Loudly crying face": "😭",
  "Screaming face": "😱",
  "Confounded face": "😖",
  "Persevering face": "😣",
  "Disapointed face": "😞",
  "Downcast face with sweat": "😓",
  "Weary face": "😩",
  "Tired face": "😫",
  "Yawning face": "🥱",
  "Face with steam": "😤",
  "Pouting face": "😡",
  "Angry face": "😠",
  "Face with symbols on mouth": "🤬",
  "Smiling face with horns": "😈",
  "Angry face with horns": "👿",
  Skull: "💀",
  "Skull and cross-bone": "☠",
  "Pile of poo": "💩",
  Clown: "🤡",
  Ogre: "👹",
  Goblin: "👺",
  Ghost: "👻",
  Alien: "👽",
  "Alien monster": "👾",
  Robot: "🤖",
  "Grinnig cat": "😺",
  "Grinning cat with smiling eyes": "😸",
  "Grinning cat with tears": "😹",
  "Smiling cat with heart eyes": "😻",
  "Cat with wry smile": "😼",
  "Kissing cat": "😽",
  "Weary cat": "🙀",
  "Crying cat": "😿",
  "Pouting cat": "😾",
  "See no evil monkey": "🙈",
  "Hear no evil monkey": "🙉",
  "Speak no evil monkey": "🙊",
  Kiss: "💏",
  "Love letter": "💌",
  "Heart with arrow": "💘",
  "HEart with ribbon": "💝",
  "Sparking heart": "💖",
  "Growing heart": "💗",
  "Beating heart": "💓",
  "Revolving heart": "💞",
  "Two hearts": "💕",
  "Heart decoration": "💟",
  "Heart exclamation": "❣",
  "Broken heart": "💔",
  "Heart on fire": "❤️‍🔥",
  "Mending heart": "❤️‍🩹",
  "Red heart": "❤",
  "Orange heart": "🧡",
  "Yellow heart": "💛",
  "Green heart": "💚",
  "Blue heart": "💙",
  "Purple heart": "💜",
  "Brown heart": "🤎",
  "Black heart": "🖤",
  "White heart": "🤍",
  "Hundred(correct)": "💯",
  Anger: "💢",
  collision: "💥",
  Dizzy: "💫",
  "Sweat droplets": "💦",
  "Dashing away": "💨",
  Hole: "🕳",
  Bomb: "💣",
  "Message baloon": "💬",
  "Eye in speech bubble": "👁️‍🗨️",
  "Left speech bubble": "🗨",
  "Anger bubble": "🗯",
  "Thought baloon": "💭",
  zzz: "💤",
  "Waving hand": "👋",
  "Raised back of hand": "🤚",
  "Hands with splayed finger": "🖐",
  "Raised hand": "✋",
  "Vulcan salute": "🖖",
  Ok: "👌",
  "Pinched fingers": "🤌",
  "Pinched hand": "🤏",
  "Victory hand": "✌",
  "Crossed fingers": "🤞",
  "Love you": "🤟",
  "Horn sign": "🤘",
  "Call me hand": "🤙",
  "Index finger pointing left": "👈",
  "Index finger pointing right": "👉",
  "Index finger pointing up": "👆",
  "Index finger pointing down": "👇",
  "Middle finger": "🖕",
  "Forehand Index finger pointing up": "☝",
  "Index finger pointing at viewer": "🫵",
  "Thumbs up": "👍",
  "Thumbs down": "👎",
  "Raised fist": "✊",
  Fist: "👊",
  "Left facing fist": "🤛",
  "Right facing fist": "🤜",
  "Clapping hands": "👏",
  "Raised hands": "🙌",
  "OPen hands": "👐",
  "Palms together hands": "🤲",
  Handshake: "🤝",
  "Praying hands": "🙏",
  "Writing hands": "✍",
  "Nail polish": "💅",
  "Selfie hand": "🤳",
  "Flexed biceps": "💪",
  "MEchanical arm": "🦾",
  Leg: "🦵",
  "Mechanical leg": "🦿",
  Foot: "🦶",
  Ear: "👂",
  "Ear with earing aid": "🦻",
  Nose: "👅",
  Brain: "🧠",
  Footprint: "👣",
  "MEchanical heart": "🫀",
  Lungs: "🫁",
  Tooth: "🦷",
  Bone: "🦴",
  Eyes: "👀",
  Eye: "👁",
  Mouth: "👄",
  Person: "🧑",
  Baby: "👶",
  Child: "🧒",
  Boy: "👦",
  Girl: "👧",
  "Person with blonde hair": "👱",
  Man: "👨",
  "Bearded person": "🧔",
  "Bearded man": "🧔‍♂‍",
  "Bearded woman": "🧔‍♀‍",
  "MAn with red hair": "👨‍🦰",
  "Man with curly hair": "👨‍🦱",
  "Man with white hair": "👨‍🦳",
  "Bald man": "👨‍🦲",
  Woman: "👩",
  "Woman with red hair": "👩‍🦰",
  "Woman with curly hair": "👩‍🦱",
  "Woman with white hair": "👩‍🦳",
  "Bald woman": "👩‍🦲",
  "Woman with blode hair": "👱‍♀‍",
  "Man with blonde hair": "👱‍♂‍",
  "Old person": "🧓",
  "Old man": "👴",
  "Old woman": "👵",
  "Person frowning": "🙍",
  "Man frowning": "🙍‍♂‍",
  "Woman frowning": "🙍‍♀‍",
  "Person pouting": "🙎",
  "Man pouting": "🙎‍♂‍",
  "Woman pouting": "🙎‍♀‍",
  "Person gesturing no": "🙅",
  "Man gesturing no": "🙅‍♂‍",
  "Woman gesturing no": "🙅‍♀‍",
  "Person stretching": "🙆",
  "Man stretching": "🙆‍♂‍",
  "Woman stretching": "🙆‍♀‍",
  "Person tipping hand": "💁",
  "Man tipping hand": "💁‍♂‍",
  "Woman tipping hand": "💁‍♀‍",
  "Person rainsing hand": "🙋",
  "Man raising hand": "🙋‍♂‍",
  "Woman raisning hand": "🙋‍♀‍",
  "Deaf person": "🧏",
  "Deaf man": "🧏‍♂‍",
  "Deaf woman": "🧏‍♀‍",
  "Person bowing": "🙇",
  "Man bowing": "🙇‍♂‍",
  "Woman bowing": "🙇‍♀‍",
  "Person facepalming": "🤦",
  "Man facepalming": "🤦‍♂‍",
  "Woman facepalming": "🤦‍♀‍",
  "Person shrugging": "🤷",
  "Man shrugging": "🤷‍♂‍",
  "Woman shrugging": "🤷‍♀‍",
  "Health worker": "🧑‍⚕‍",
  "Man health worker": "👨‍⚕‍",
  "Woman health worker": "👩‍⚕‍",
  Student: "🧑‍🎓",
  "Man student": "👨‍🎓",
  Teacher: "🧑‍🏫",
  "Man teacher": "👨‍🏫",
  "Woman teacher": "👩‍🏫",
  Judge: "🧑‍⚖‍",
  "Man judge": "👨‍⚖‍",
  "Woman judge": "👩‍⚖‍",
  Farmer: "🧑‍🌾",
  "Man farmer": "👨‍🌾",
  "Woman farmer": "👩‍🌾",
  Cook: "🧑‍🍳",
  "Man cook": "👨‍🍳",
  "Woman cook": "👩‍🍳",
  Mechanic: "🧑‍🔧",
  "Man mechanic": "👨‍🔧",
  "Woman mechanic": "👩‍🔧",
  "Factory worker": "🧑‍🏭",
  "Man factory worker": "👨‍🏭",
  "Woman factory worker": "👩‍🏭",
  "Office worker": "🧑‍💼",
  "Man office worker": "👨‍💼",
  "Woma office worker": "👩‍💼",
  Scientist: "🧑‍🔬",
  "Man scientist": "👨‍🔬",
  "Woman scientist": "👩‍🔬",
  Technologist: "🧑‍💻",
  "Man texhnologist": "👨‍💻",
  "Woman technologist": "👩‍💻",
  Singer: "🧑‍🎤",
  "Man singer": "👨‍🎤",
  "Woman singer": "👩‍🎤",
  Artist: "🧑‍🎨",
  "Man artist": "👨‍🎨",
  "Woman artist": "👩‍🎨",
  Pilot: "🧑‍✈‍",
  "Man pilot": "👨‍✈‍",
  "Woman pilot": "👩‍✈‍",
  Astronaut: "🧑‍🚀",
  "Man astronaut": "👨‍🚀",
  "Woman astronaut": "👩‍🚀",
  Firefighter: "🧑‍🚒",
  "Man firefighter": "👨‍🚒",
  "Woman firefighter": "👩‍🚒",
  Police: "👮",
  Policeman: "👮‍♂‍",
  Policewoman: "👮‍♀‍",
  Detective: "🕵",
  "Man detective": "🕵️‍♂‍",
  "Woman detective": "🕵️‍♀‍",
  Guard: "💂",
  "Man guard": "💂‍♂‍",
  "Woman guard": "💂‍♀‍",
  Ninja: "🥷",
  "Construction worker": "👷",
  "Man construction worker": "👷‍♂‍",
  "Woman construction worker": "👷‍♀‍",
  Prince: "🤴",
  Princess: "👸",
  "Person wearing turban": "👳",
  "Man wearing turban": "👳‍♂‍",
  "Woman wearing turban": "👳‍♀‍",
  "Person with skullcap": "👲",
  "Woman with headscaff": "🧕",
  "Person in tuxedo": "🤵",
  "Man in tuxedo": "🤵‍♂‍",
  "Woman in tuxedo": "🤵‍♀‍",
  "Person in veil": "👰",
  "Man in veil": "👰‍♂‍",
  "Woman in veil": "👰‍♀‍",
  "Pregnant woman": "🤰",
  "Breast-feeding": "🤱",
  "Person feeding baby": "🧑‍🍼",
  "WOman feeding baby": "👩‍🍼",
  "Man feeding baby": "👨‍🍼",
  "Baby angel": "👼",
  "Santa claus": "🎅",
  "Mrs Claus": "🤶",
  "Mx Claus": "🧑‍🎄",
  Superhero: "🦸",
  "Man superhero": "🦹‍♂‍",
  "Woman superhero": "🦹‍♀‍",
  Supervillain: "🦹",
  Mage: "🧙",
  "Man mage": "🧙‍♂‍",
  "Woman mage": "🧙‍♀‍",
  Fairy: "🧚",
  "Man fairy": "🧚‍♂‍",
  "Woman fairy": "🧚‍♀‍",
  Vampire: "🧛",
  "Man vampire": "🧛‍♂‍",
  "Woman vampire": "🧛‍♀‍",
  Merperson: "🧜",
  Merman: "🧜‍♂‍",
  Mermaid: "🧜‍♀‍",
  Elf: "🧝",
  "Man elf": "🧝‍♂‍",
  "Woman elf": "🧝‍♀‍",
  Genie: "🧞",
  "Man genie": "🧞‍♂‍",
  "Woman genie": "🧞‍♀‍",
  Zombie: "🧟",
  "Man zombie": "🧟‍♂‍",
  "Woman zombie": "🧟‍♀‍",
  "Person getting massage": "💆",
  "Man getting massage": "💆‍♂‍",
  "Woman getting massage": "💆‍♀‍",
  "Person getting haircut": "💇",
  "Man getting haircut": "💇‍♂‍",
  "Woman getting haircut": "💇‍♀‍",
  "Person walking": "🚶",
  "Man walking": "🚶‍♂‍",
  "Woman walking": "🚶‍♀‍",
  "Person standing": "🧍",
  "Man standing": "🧍‍♂‍",
  "Woman standing": "🧍‍♀‍",
  "Person kneeling": "🧎",
  "Man kneeling": "🧎‍♂‍",
  "Woman kneeling": "🧎‍♀‍",
  "PErson with walking stick": "🧑‍🦯",
  "Man with walking stick": "👨‍🦯",
  "Woman with walking stick": "👩‍🦯",
  "Person in motorized wheelchair": "🧑‍🦼",
  "Man in motorized wheelchair": "👨‍🦼",
  "Womain in motorized wheelchair": "👩‍🦼",
  "Person in manual wheelchair": "🧑‍🦽",
  "Man in manual wheelchair": "👨‍🦽",
  "Womaan in motorized wheelchair": "👩‍🦽",
  "Person sprinting": "🏃",
  "Man sprinting": "🏃‍♂‍",
  "Woman sprinting": "🏃‍♀‍",
  "Woman dancing": "💃",
  "Man dancing": "🕺",
  "Person in suit levitating": "🕴",
  "People with bunny ears": "👯",
  "Men with bunny ears": "👯‍♂‍",
  "Women in bunny ears": "👯‍♀‍",
  "Person in steaming room": "🧖",
  "Man in steaming room": "🧖‍♂‍",
  "Woman in steaming room": "🧖‍♀‍",
  "Person climbing": "🧗",
  "Man climbing": "🧗‍♂‍",
  "Woman climbing": "🧗‍♀‍",
  "Person fencing": "🤺",
  "Horse racing": "🏇",
  Skier: "⛷",
  Snowball: "🏂",
  "Person playing golf": "🏌",
  "Man playing golf": "🏌️‍♂‍",
  "Woman playing golf": "🏌️‍♀‍",
  "Person surfing": "🏄",
  "Man surfing": "🏄‍♂‍",
  "Woman surfing": "🏄‍♀‍",
  "Person rowing boat": "🚣",
  "Man rowing boat": "🚣‍♂‍",
  "Woman rowing boat": "🚣‍♀‍",
  "Person swimming": "🏊",
  "Man swimming": "🏊‍♂‍",
  "Woman swimming": "🏊‍♀‍",
  "Person bouncing ball": "⛹",
  "Man bouncing ball": "⛹️‍♂‍",
  "Woman bouncing ball": "⛹️‍♀‍",
  "Person lifting weight": "🏋",
  "Man lifting weight": "🏋️‍♂‍",
  "Woman lifting weight": "🏋️‍♀‍",
  "Person cycling": "🚴",
  "Man cycling": "🚴‍♂‍",
  "Woman cycling": "🚴‍♀‍",
  "Person mountain biking": "🚵",
  "Man mountain biking": "🚵‍♂‍",
  "Woman mountain biking": "🚵‍♀‍",
  "Person catwheeling": "🤸",
  "Man catwheeling": "🤸‍♂‍",
  "Woman catwheeling": "🤸‍♀‍",
  "People wrestling": "🤼",
  "Men wrestling": "🤼‍♂‍",
  "Women wrestling": "🤼‍♀‍",
  "Person playing water polo": "🤽",
  "Man playing water polo": "🤽‍♂‍",
  "Woman playing water polo": "🤽‍♀‍",
  "Person playing handball": "🤾",
  "Man playing handball": "🤾‍♂‍",
  "Woman playing handball": "🤾‍♀‍",
  "Person juggling": "🤹",
  "Man juggling": "🤹‍♂‍",
  "Woman juggling": "🤹‍♀‍",
  "Person lotus position": "🧘",
  "Man in lotus position": "🧘‍♂‍",
  "Woman in lotus position": "🧘‍♀‍",
  "Person bathing": "🛀",
  "Person in bed": "🛌",
  Family: "👪",
  "Family: man, woman, and boy": "👨‍👩‍👦",
  "Family: man, woman, and girl": "👨‍👩‍👧",
  "Family: man, woman, boy, and girl": "👨‍👩‍👧‍👦",
  "Family: man, woman, and two boys": "👨‍👩‍👦‍👦",
  "Family: man, woman, and two girls": "👨‍👩‍👧‍👧",
  "Family: two men and boy": "👨‍👨‍👦",
  "Family: two men and girl": "👨‍👨‍👧",
  "Family: two men, girl, and boy": "👨‍👨‍👧‍👦",
  "Family: two men and two boys": "👨‍👨‍👦‍👦",
  "Family: two men and two girls": "👨‍👨‍👧‍👧",
  "Family: two women and boy": "👩‍👩‍👦",
  "Family: two women and girl": "👩‍👩‍👧",
  "Family: two women, girl, and boy": "👩‍👩‍👧‍👦",
  "Family: two women and two boys": "👩‍👩‍👦‍👦",
  "Family: two women and two girls": "👩‍👩‍👧‍👧",
  "Family: man and boy": "👨‍👦",
  "Family: man and two boys": "👨‍👦‍👦",
  "Family: man and girl": "👨‍👧",
  "Family: man, girl and boy": "👨‍👧‍👦",
  "Family: man and two girls": "👨‍👧‍👧",
  "Family: woman and boy": "👩‍👦",
  "Family: woman and two boys": "👩‍👦‍👦",
  "Family: woman and girl": "👩‍👧",
  "Family: woman, girl, and boy": "👩‍👧‍👦",
  "Family: woman and two girls": "👩‍👧‍👧",
  "People holding hands": "🧑‍🤝‍🧑",
  "Women holding hands": "👭",
  "Woman and man holding hands": "👫",
  "Men holding hands": "👬",
  "Woman and man kissing": "👩‍❤‍💋‍👨",
  "Man and man kissing": "👨‍❤‍💋‍👨",
  "Womand and woman kissing": "👩‍❤‍💋‍👩",
  "Couple with heart": "💑",
  "Person speaking": "🗣",
  "Bust in silhouhette": "👤",
  "Busts in silhouette": "👥",
  "People hugging": "🫂",
  "Monkey face": "🐵",
  Monkey: "🐒",
  Gorilla: "🦍",
  Orangutan: "🦧",
  "Dog face": "🐶",
  Dog: "🐕",
  "Guide dog": "🦮",
  "Service dog": "🐕‍🦺",
  Poodle: "🐩",
  Wolf: "🐺",
  Fox: "🦊",
  Racoon: "🦝",
  "Cat face": "🐱",
  Cat: "🐈",
  "Black cat": "🐈‍⬛",
  Lion: "🦁",
  "Tiger face": "🐯",
  Tiger: "🐅",
  Leopard: "🐆",
  "Horse face": "🐴",
  Horse: "🐎",
  Unicorn: "🦄",
  Zebra: "🦓",
  Deer: "🦌",
  Bison: "🦬",
  "Cow face": "🐮",
  Cow: "🐄",
  Ox: "🐂",
  "Water buffalo": "🐃",
  "Pig face": "🐷",
  Pig: "🐖",
  Boar: "🐗",
  "Pig nose": "🐽",
  Ram: "🐏",
  Ewe: "🐑",
  Goat: "🐐",
  Camel: "🐪",
  "Two hump camel": "🐫",
  Ilama: "🦙",
  Giraffe: "🦒",
  Elephant: "🐘",
  Mammoth: "🦣",
  Rhiniceros: "🦏",
  Hippopotamus: "🦛",
  "Mouse face": "🐭",
  Mouse: "🖱",
  Rat: "🐀",
  Hamster: "🐹",
  "Rabbit face": "🐰",
  Rabbit: "🐇",
  Chipmunk: "🐿",
  Beaver: "🦫",
  Hedgehog: "🦔",
  Bat: "🦇",
  Bear: "🐻",
  "Polar bear": "🐻‍❄️",
  Koala: "🐨",
  Panda: "🐼",
  Sloth: "🦥",
  Otter: "🦦",
  Skunk: "🦨",
  Kangaroo: "🦘",
  Badger: "🦡",
  "Paw prints": "🐾",
  Turkey: "🦃",
  Chicken: "🐔",
  Rooster: "🐓",
  Hatching: "🐣",
  "Baby chick": "🐤",
  "Front-facing chick": "🐥",
  Bird: "🐦",
  Penguin: "🐧",
  Dove: "🕊",
  Eagle: "🦅",
  Duck: "🦆",
  Swan: "🦢",
  Owl: "🦉",
  Dodo: "🦤",
  Feather: "🪶",
  Flamingo: "🦩",
  Peacock: "🦜",
  Frog: "🐸",
  Crocodile: "🐊",
  Turtle: "🐢",
  Lizard: "🦎",
  Snake: "🐍",
  "Dragon face": "🐲",
  Dragon: "🐉",
  Sauropod: "🦕",
  Tyranosaurus: "🦖",
  "Spouting whale": "🐳",
  Whale: "🐋",
  Dolphin: "🐬",
  Seal: "🦭",
  Fish: "🐟",
  "Tropical fish": "🐠",
  Blowfish: "🐡",
  Shark: "🦈",
  Octopus: "🐙",
  "Spiral shell": "🐚",
  Snail: "🐌",
  Butterfly: "🦋",
  Bug: "🐛",
  Ant: "🐜",
  Honeybee: "🐝",
  Beetle: "🪲",
  "Lady Beetle": "🐞",
  Cricket: "🏏",
  Cockroach: "🪳",
  Spider: "🕷",
  "Spider web": "🕸",
  Scorpion: "🦂",
  Mosquito: "🦟",
  Fly: "🪰",
  Worm: "🪱",
  Microbe: "🦠",
  Bouquet: "💐",
  "Cherry blossom": "🌸",
  "White flower": "💮",
  Rosette: "🏵",
  Rose: "🌹",
  "Wilted flower": "🥀",
  Hibiscus: "🌺",
  Sunflower: "🌻",
  Blossom: "🌼",
  Tulip: "🌷",
  Seedling: "🌱",
  "Potted plant": "🪴",
  "Evergreen tree": "🌲",
  "Deciduous plant": "🌳",
  "Palm tree": "🌴",
  Cactus: "🌵",
  "Sheaf of rice": "🌾",
  Herb: "🌿",
  Shamrock: "☘",
  "Four leaf clover": "🍀",
  "Maple leaf": "🍁",
  "Fallen leaf": "🍂",
  "Leaf fluttering in wind": "🍃",
  "Empty nest": "🪴",
  "Nest with eggs": "🪴",
  Grapes: "🍇",
  Melon: "🍈",
  "Water melon": "🍉",
  Tangerine: "🍊",
  Lime: "🍋",
  Banana: "🍌",
  Pineapple: "🍍",
  Mango: "🥭",
  "Red apple": "🍎",
  "Green apple": "🍏",
  Pear: "🍐",
  Peach: "🍑",
  Cherries: "🍒",
  Strawberries: "🍓",
  Blueberries: "🫐",
  "Kiwi fruit": "🥝",
  Tomato: "🍅",
  Olive: "🫒",
  Coconut: "🥥",
  Avocado: "🥑",
  Eggplant: "🍆",
  Potato: "🥔",
  Carrot: "🥕",
  Corn: "🌽",
  Pepper: "🌶",
  "Bell pepper": "🫑",
  Cucumber: "🥒",
  "Leafy green": "🥬",
  Broccoli: "🥦",
  Garlic: "🧄",
  Onion: "🧅",
  Mushroom: "🍄",
  Peanuts: "🥜",
  Beans: "🫑",
  Chestnut: "🌰",
  Bread: "🍞",
  Croissant: "🥐",
  "Baguette bread": "🥖",
  "Flat bread": "🫓",
  Pretzel: "🥨",
  Bagel: "🥯",
  Pancake: "🥞",
  Waffle: "🧇",
  "Cheese wedge": "🧀",
  "Meat with bone": "🍖",
  "Poultry leg": "🍗",
  "Cut of meat": "🥩",
  Bacon: "🥓",
  Hamburger: "🍔",
  "French fries": "🍟",
  Pizza: "🍕",
  "Hot dog": "🌭",
  Sandwich: "🥪",
  Taco: "🌮",
  Burrito: "🌯",
  Tamale: "🫔",
  "Stuffed flatbread": "🥙",
  Falafel: "🧆",
  Egg: "🥚",
  Cooking: "🍳",
  "Shallow pan of food": "🥘",
  "Pot of food": "🍲",
  Fondue: "🫕",
  "Bowl with food": "🥣",
  "Green salad": "🥗",
  Popcorn: "🍿",
  Butter: "🧈",
  Salt: "🧂",
  "Canned food": "🥫",
  "Bento box": "🍱",
  "RIce cracker": "🍘",
  "Rice ball": "🍙",
  "Cooked rice": "🍚",
  "Curry rice": "🍛",
  "Steaming bowl": "🍜",
  Spaghetti: "🍝",
  "Roasted sweet potato": "🍠",
  Oden: "🍢",
  Sushi: "🍣",
  "Fried shrimp": "🍤",
  "Fish cake with swiri": "🍥",
  "Moon cake": "🥮",
  Dango: "🍡",
  Dumpling: "🥟",
  "Fortune cookie": "🥠",
  "Take out box": "🥡",
  Crab: "🦀",
  Lobster: "🦞",
  Shrimp: "🦐",
  Squid: "🦑",
  Oyster: "🦪",
  "Ice cream": "🍨",
  "Shaved ice cream": "🍧",
  "Soft ice cream": "🍦",
  Doughnut: "🍩",
  Cookie: "🍪",
  "Birthday cake": "🎂",
  "Short cake": "🍰",
  "Cup cake": "🧁",
  Pie: "🥧",
  Chocoloate: "🍫",
  Candy: "🍬",
  Lollipop: "🍭",
  Custard: "🍮",
  "Honey pot": "🍯",
  "Baby bottle": "🍼",
  "Glass of milk": "🥛",
  "Hot beverage": "☕",
  Teapot: "🫖",
  "Teacup without handle": "🍵",
  Sake: "🍶",
  "Bottle with poppin cork": "🍾",
  "Wine glass": "🍷",
  "Cocktail glass": "🍸",
  "Tropical drink": "🍹",
  "Beer mug": "🍺",
  "Clinking beer mug": "🍻",
  "Clinking glasses": "🥂",
  "Tumbler glass": "🥃",
  "Cup with strawberry": "🥤",
  "Bubble tea": "🧋",
  "Beverage box": "🧃",
  Mate: "🧉",
  Ice: "🧊",
  Chopsticks: "🥢",
  "Fork and knife with plate": "🍽",
  "Fork and knife": "🍴",
  Spoon: "🥄",
  "Kitchen knife": "🔪",
  Jar: "🧋",
  Amphora: "🏺",
  "Globe showing Africa and Europe": "🌍",
  "Globe showing Americas": "🌎",
  "Globe showing Asia and Australia": "🌏",
  "Globe with meridians": "🌐",
  "World map": "🗺",
  Compass: "🧭",
  Mountain: "⛰",
  "Snowcap mountain": "🏔",
  "Volcanic mountain": "🌋",
  "Fuji mountain": "🗻",
  Camping: "🏕",
  "Beach with umbrella": "🏖",
  Desert: "🏜",
  "Desertified island": "🏝",
  "National park": "🏞",
  Stadium: "🏟",
  "Classical building": "🏛",
  "Building construction": "🏗",
  Brick: "🧱",
  Rock: "🪨",
  Wood: "🪵",
  Hut: "🛖",
  Houses: "🏘",
  "Derelict house": "🏚",
  House: "🏠",
  "House with garden": "🏡",
  "Office building": "🏢",
  "Japanese office": "🏣",
  "Post office": "🏤",
  Hospital: "🏥",
  Bank: "🏦",
  Hotel: "🏨",
  "Love hotel": "🏩",
  "Convenience store": "🏪",
  School: "🏫",
  Department: "🏬",
  Factory: "🏭",
  "Japanese castle": "🏯",
  Castle: "🏰",
  "Wedding house": "💒",
  "Tokyo tower": "🗼",
  "Statue of liberty": "🗽",
  Church: "⛪",
  Mosque: "🕌",
  "Hindu temple": "🛕",
  Synagogue: "🕍",
  "Shinto shrine": "⛩",
  Kaaba: "🕋",
  Fountain: "⛲",
  Tent: "⛺",
  Foggy: "🌁",
  "Night with starrs": "🌃",
  Citscape: "🏙",
  Sunrise: "🌅",
  "Sunrise over mountains": "🌄",
  "Cityscape at dusk": "🌆",
  Sunset: "🌇",
  "Bridge at night": "🌉",
  "Hot springs": "♨",
  "Carousel horse": "🎠",
  "Ferris wheel": "🎡",
  "Roller coaster": "🎢",
  "Barber poll": "💈",
  "Circus tent": "🎪",
  Locomotive: "🚂",
  "Railway car": "🚃",
  "High speed train": "🚄",
  "Bullet train": "🚅",
  Train: "🚆",
  Metro: "🚇",
  "Light rail": "🚈",
  Station: "🚉",
  Tram: "🚊",
  Monorail: "🚝",
  "Mountain railway": "🚞",
  "Tram car": "🚋",
  us: "🚌",
  "Oncoming bus": "🚍",
  "Trolley bus": "🚎",
  Minibus: "🚐",
  Ambulance: "🚑",
  "Fire engine": "🚒",
  "Police car": "🚓",
  "Oncoming police car": "🚔",
  Taxi: "🚕",
  "Oncoming taxi": "🚖",
  Automobile: "🚗",
  "Oncoming automobile": "🚘",
  "Sport utility vehicle": "🚙",
  "Pickup truck": "🛻",
  "Delivery truck": "🚚",
  "Articulated lorry": "🚛",
  Tractor: "🚜",
  "Racing car": "🏎",
  Motorcycle: "🏍",
  Scooter: "🛵",
  "Manual wheelchair": "🦽",
  "Motorized wheelchair": "🦼",
  "Hourglass done": "⌛",
  "Hourglass starting": "⏳",
  Watch: "⌚",
  Alarm: "⏰",
  Stopwatch: "⏱",
  "Timer clock": "⏲",
  "Mantelpiece clock": "🕰",
  "Twelve O'clock": "🕛",
  "Twelve-thirty": "🕧",
  "One O'clock": "🕐",
  "One-thirty": "🕜",
  "Two O'clock": "🕑",
  "Two-thirty": "🕝",
  "Three O'clock": "🕒",
  "Three-thirty": "🕞",
  "Four O'clock": "🕓",
  "Four-thirty": "🕟",
  "Five O'clock": "🕔",
  "Five-thirty": "🕠",
  "Six O'clock": "🕕",
  "Six-thirty": "🕡",
  "Seven O'clock": "🕖",
  "Seven-thirty": "🕢",
  "Eight O'clock": "🕗",
  "Eight-thirty": "🕣",
  "Nine O'clock": "🕘",
  "Nine-thirty": "🕤",
  "Ten O'clock": "🕙",
  "Ten-thirty": "🕥",
  "Eleven O'clock": "🕚",
  "Eleven-thirty": "🕦",
  "New moon": "🌑",
  "Waxing crescent moon": "🌒",
  "First quarter moon": "🌓",
  "Waxing gibbous moon": "🌔",
  "Full moon": "🌕",
  "Waning gibbous moon": "🌖",
  "Last quarter moon": "🌗",
  "Waning crescent moon": "🌘",
  "Crescent moon": "🌙",
  "New moon face": "🌚",
  "First quarter moon face": "🌛",
  "Last quartermoon face": "🌜",
  Thermometer: "🌡",
  Sun: "☀",
  "Full moon face": "🌝",
  "Sun with face": "🌞",
  "Ringed planet": "🪐",
  Star: "⭐",
  "Glowing star": "🌟",
  "Shooting star": "🌠",
  "Milky way": "🌌",
  Cloud: "☁",
  "Sun behind cloud": "⛅",
  "Cloud with lighting and rain": "⛈",
  "Sun behind small cloud": "🌤",
  "Sun behind large cloud": "🌥",
  "Sun behind rain cloud": "🌦",
  "Cloud with rain": "🌧",
  "Cloud with snow": "🌨",
  "Cloud with lighting": "🌩",
  Tornado: "🌪",
  Fog: "🌫",
  "Wind face": "🌬",
  Cyclone: "🌀",
  Rainbow: "🌈",
  "Closed umbrella": "🌂",
  Umbrella: "☂",
  "Umbrella with raindrops": "☔",
  "Umbrella on ground": "⛱",
  "High voltage": "⚡",
  Snowflake: "❄",
  Snowman: "☃",
  "Snowman without snow": "⛄",
  Comet: "☄",
  Fire: "🔥",
  Droplet: "💧",
  "Water wave": "🌊",
  "Jack-o-lantern": "🎃",
  "Christmas tree": "🎄",
  Fireworks: "🎆",
  Sparkler: "🎇",
  Firecracker: "🧨",
  Sparkles: "✨",
  Baloon: "🎈",
  "Party popper": "🎉",
  "Confetti ball": "🎊",
  "Tanabata tree": "🎋",
  "Pine decoration": "🎍",
  "Japanese dolls": "🎎",
  "Carp streamer": "🎏",
  "Moon viewing ceremony": "🎑",
  "Red envelope": "🧧",
  Ribbon: "🎀",
  "Wrapped gift": "🎁",
  "Reminder ribbon": "🎗",
  "Admission ticket": "🎟",
  Ticket: "🎫",
  "Military medal": "🎖",
  Trophy: "🏆",
  "Sports medal": "🏅",
  "Gold medal - first position": "🥇",
  "Silver medal - second position": "🥈",
  "Bronze medal - third position": "🥉",
  "Soccer ball": "⚽",
  Baseball: "⚾",
  Softball: "🥎",
  BAsketball: "🏀",
  Volleyball: "🏐",
  "American football": "🏈",
  Rugby: "🏉",
  Tennis: "🎾",
  "Flying disk": "🥏",
  Bowling: "🎳",
  "Field hockey": "🏑",
  "Ice hockey": "🏒",
  Lacrose: "🥍",
  "Ping pong": "🏓",
  Badminton: "🏸",
  "Boxing glove": "🥊",
  "Martial arts uniform": "🥋",
  "Goal net": "🥅",
  "Flag in a hole": "⛳",
  "Ice skate": "⛸",
  "Fishing poll": "🎣",
  "Driving mask": "🤿",
  "Running shirt": "🎽",
  Skis: "🎿",
  Sled: "🛷",
  "Curling stone": "🥌",
  Bullseye: "🎯",
  "Yo-yo": "🪀",
  Kite: "🪁",
  "8 ball": "🎱",
  "Crystal ball": "🔮",
  "Magic wand": "🪄",
  "Nazar amulet": "🧿",
  Hamsa: "🪄",
  "Video game pad": "🎮",
  Joystick: "🕹",
  "Slot machine": "🎰",
  "Game die": "🎲",
  "Puxxle piece": "🧩",
  "Teddy bear": "🧸",
  Pinata: "🪅",
  Mirror: "🪞",
  "Nesting doll": "🪆",
  "Spade suit": "♠",
  "Heart suit": "♥",
  "Club suit": "♣",
  "Chess pawn": "♟",
  Joker: "🃏",
  "Mahjong red dragon": "🀄",
  "Flower playing cards": "🎴",
  "Performing arts": "🎭",
  "Framed picture": "🖼",
  "Artist pallete": "🎨",
  Thread: "🧵",
  "Sewing needle with thred": "🪡",
  Yarn: "🧶",
  Knot: "🪢",
  Glasses: "👓",
  Sunglasses: "🕶",
  Googles: "🥽",
  "Lab coat": "🥼",
  "Safety vest": "🦺",
  Necktie: "👔",
  "T-shirt": "👕",
  Jeans: "👖",
  Scarf: "🧣",
  Gloves: "🧤",
  Coat: "🧥",
  Socks: "🧦",
  Dress: "👗",
  Kimono: "👘",
  Sari: "🥻",
  "One piece suit": "🩱",
  Briefs: "🩲",
  Shorts: "🩳",
  Bikini: "👙",
  "Woman's cloth": "👚",
  Purse: "👛",
  Handbag: "👜",
  "Clutch bag": "👝",
  "Shopping bags": "🛍",
  Backpack: "🎒",
  "Thong sandals": "🩴",
  "Man's shoe": "👞",
  "Running shoe": "👟",
  "Hiking boot": "🥾",
  "Flat shoe": "🥿",
  "High-heeled shoe": "👠",
  "Woman's sandal": "👡",
  "Ballet shoes": "🩰",
  "Woman's boot": "👢",
  Crown: "👑",
  "Woman's hat": "👒",
  "Top hat": "🎩",
  "Graduation cap": "🎓",
  "Billed cap": "🧢",
  "Military helmet": "🪖",
  "Rescuew worker's helmet": "⛑",
  "PRayer beads": "📿",
  Lipstick: "💄",
  Ring: "💍",
  Gemstone: "💎",
  "Muted speaker": "🔇",
  "Low volume speaker": "🔈",
  "Mid volume speaker": "🔉",
  "High volume speaker": "🔊",
  Loudspeaker: "📢",
  Megaphone: "📣",
  "Postal horn": "📯",
  Bell: "🔔",
  "Bell with slash": "🔕",
  "Musical score": "🎼",
  "Musical note": "🎵",
  "Musical notes": "🎶",
  "Studio microphone": "🎙",
  "Level slider": "🎚",
  "Control knobs": "🎛",
  Microphone: "🎤",
  Headphone: "🎧",
  Radio: "📻",
  Saxophone: "🎷",
  Accordion: "🪗",
  Guitar: "🎸",
  "Musical keyboard": "🎹",
  Trumpet: "🎺",
  Violin: "🎻",
  Banjo: "🪕",
  Drum: "🥁",
  "Long drum": "🪘",
  "Mobile phone": "📱",
  "MObile phone with arrow": "📲",
  Telephone: "☎",
  "Telephone receiver": "📞",
  Pager: "📟",
  "Fax machine": "📠",
  "Full battery": "🔋",
  "Low battery": "🪫",
  "Electric plug": "🔌",
  Laptop: "💻",
  "Desktop computer": "🖥",
  Printer: "🖨",
  Keyboard: "⌨",
  Trackball: "🖲",
  "Computer disk": "💽",
  "Floppy disk": "💾",
  "Optical disk": "💿",
  DVD: "📀",
  Abacus: "🧮",
  "Movie camera": "🎥",
  "Film frames": "🎞",
  "Film Projector": "📽",
  "Clapper board": "🎬",
  Television: "📺",
  Camera: "📷",
  "Camera with flash": "📸",
  "Video camera": "📹",
  "Video cassete": "📼",
  "Magnifying glass tilted left": "🔍",
  "Magnifying glass tilted right": "🔎",
  Candle: "🕯",
  "Light bulb": "💡",
  Flashlight: "🔦",
  "Red pepper lantern": "🏮",
  "Diya lamp": "🪔",
  "Notebook with decorative cover": "📔",
  "Closed notebook": "📕",
  "Opened notebook": "📖",
  "Green book": "📗",
  "Blue book": "📘",
  "Orange book": "📙",
  "Orange books": "📚",
  Notebook: "📓",
  Ledger: "📒",
  "Page with curl": "📃",
  Scroll: "📜",
  "Page facing up": "📄",
  Newspaper: "📰",
  "Rolled-up newspaper": "🗞",
  "Bookmark tabs": "📑",
  Bookmark: "🔖",
  Label: "🏷",
  "Money bag": "💰",
  Coin: "🪙",
  "Yen banknote": "💴",
  "Dollar banknote": "💵",
  "Euro banknote": "💶",
  "Pound banknote": "💷",
  "Money with wings": "💸",
  "Credit card": "💳",
  Receipt: "🧾",
  "Chart increase woth Yen": "💹",
  Envelope: "✉",
  "e-mail": "📧",
  "Envelope with arrow": "📩",
  "Outbox tray": "📤",
  "Inbox tray": "📥",
  Package: "📦",
  "Closed mailbox with raised flag": "📫",
  "Closed mailbox with lowered flag": "📪",
  "Open mailbox with raised flag": "📬",
  "Open mailbox with lowered flag": "📭",
  Postbox: "📮",
  "Ballot box with ballot": "🗳",
  Pencil: "✏",
  "Black nib": "✒",
  "Fountain pen": "🖋",
  Pen: "🖊",
  Paintbrush: "🖌",
  Crayon: "🖍",
  Memo: "📝",
  Briefcase: "💼",
  "File folder": "📁",
  "Open the folder": "📂",
  "Card index dividers": "🗂",
  Calender: "📅",
  "Tear off calender": "📆",
  "Card index": "📇",
  "Increasing chart": "📈",
  "Decreasing chart": "📉",
  "Bar chart": "📊",
  Clipboard: "📋",
  Pushpin: "📌",
  "Round pushpin": "📍",
  Paperclip: "📎",
  "Linked paperclips": "🖇",
  "Straight ruler": "📏",
  "Triangular ruler": "📐",
  Scissors: "✂",
  "Card file box": "🗃",
  "File cabinet": "🗄",
  "Waste basket": "🗑",
  Locked: "🔒",
  Unlocked: "🔓",
  "Locked with pen": "🔏",
  "Locked with key": "🔐",
  Key: "🔑",
  "Old key": "🗝",
  Hammer: "🔨",
  Axe: "🪓",
  Pick: "⛏",
  "Hammer and pick": "⚒",
  "Hammer and wrench": "🛠",
  Sword: "🗡",
  "Crossed swords": "⚔",
  "Water gun": "🔫",
  Boomerang: "🪃",
  "Bow and arrow": "🏹",
  Shield: "🛡",
  "Carpentry saw": "🪚",
  Wrench: "🔧",
  Screwdriver: "🪛",
  "Bolt and nut": "🔩",
  Wheel: "⚙",
  Clamp: "🗜",
  "Balance scale": "⚖",
  "White cane": "🦯",
  Link: "🔗",
  Chains: "⛓",
  Hook: "🪝",
  Toolbox: "🧰",
  Magnet: "🧲",
  Ladder: "🪜",
  Alembic: "⚗",
  "Test tube": "🧪",
  "Petri dish": "🧫",
  DNA: "🧬",
  Microscope: "🔬",
  Telescope: "🔭",
  "Satelite antenna": "📡",
  Syringe: "💉",
  "A droplet of blood": "🩸",
  Pill: "💊",
  "Adhesive bandage": "🩹",
  Clutch: "🩼",
  Stethoscope: "🩺",
  "X-ray": "🩻",
  Door: "🚪",
  Elevator: "🛗",
  Window: "🪟",
  Bed: "🛏",
  "Couch and lamp": "🛋",
  Chair: "🪑",
  Toilet: "🚽",
  Plunger: "🪠",
  Shower: "🚿",
  Bathtub: "🛁",
  "Mouse trap": "🪤",
  Razor: "🪒",
  "Lotion bottle": "🧴",
  "Safety pin": "🧷",
  Broom: "🧹",
  Basket: "🧺",
  "Roll of paper": "🧻",
  Bucket: "🪣",
  Soap: "🧼",
  Bubbles: "🫧",
  Toothbrush: "🪥",
  Sponge: "🧽",
  "Fire extinguisher": "🧯",
  "Shopping cart": "🛒",
  Cigarette: "🚬",
  Casket: "⚰",
  Headstone: "🪦",
  "Funeral urn": "⚱",
  Mole: "🗿",
  Placard: "🪧",
  "ID Card": "🪪",
  "ATM Sign": "🏧",
  "Litter in bin": "🚮",
  "Portable water": "🚰",
  "Wheelchair symbol": "♿",
  "Men's room symbol": "🚹",
  "Women's room symbol": "🚺",
  "Restroom symbol": "🚻",
  "Baby symbol": "🚼",
  "Water closet": "🚾",
  "Passport control": "🛂",
  Customs: "🛂",
  "Baggage claim": "🛄",
  "Left laugage": "🛅",
  Warning: "⚠",
  "Children crossing": "🚸",
  "No entry": "⛔",
  Prohibited: "🚫",
  "No bicycles": "🚳",
  "No smoking": "🚭",
  "No littering": "🚯",
  "Non-portable water": "🚱",
  "No pedestrians": "🚷",
  "No mobile phones": "📵",
  "No one under 18": "🔞",
  Radioactive: "☢",
  Biohazard: "☣",
  "Up Arrow": "⬆",
  "Up-right arrow": "↗",
  "Right arrow": "➡",
  "Down-right arrow": "↘",
  "Down arrow": "⬇",
  "Down-left arrow": "↙",
  "Left arrow": "↔",
  "Up-left arrow": "↖",
  "Up-down arrow": "↕",
  "Right arrow curving left": "↩",
  "Left arrow curving right": "↪",
  "Right arrow curving up": "⤴",
  "Right arrow curving down": "⤵",
  "Clockwise vertical arrow": "🔃",
  "Counterclockwise arrows button": "🔄",
  "Back arrow": "🔙",
  "End arrow": "🔚",
  "On arrow": "🔛",
  "Soon arrow": "🔜",
  "Top arrow": "🔝",
  "Place of worship": "🛐",
  "Atom symbol": "⚛",
  OM: "🕉",
  "Star of David": "✡",
  "Wheel of Dharma": "☸",
  "Yin yang": "☯",
  "Latin cross": "✝",
  "ORthodox cross": "☦",
  "Star and cresent moon": "☪",
  Peace: "☮",
  Menorah: "🕎",
  "Six-pointed star": "🔯",
  Aries: "♈",
  Taurus: "♉",
  Gemini: "♊",
  Cancer: "♋",
  Leo: "♌",
  Virgo: "♍",
  Libra: "♎",
  Scorpio: "♏",
  Sagittarius: "♐",
  Capricon: "♑",
  Acquarius: "♒",
  Pisces: "♓",
  Ophiucus: "⛎",
  "Shuffle tracks": "🔀",
  "Repeat all": "🔁",
  "Repeat one": "🔂",
  Play: "▶",
  Pause: "⏸",
  "Fast-forward": "⏩",
  "Next track": "⏭",
  "Play or pause": "⏯",
  Reverse: "◀",
  "Fast-reverse": "⏪",
  "Previous track": "⏮",
  Upwards: "🔼",
  "Fst-up": "⏫",
  Downwards: "🔽",
  "Fast down": "⏬",
  Stop: "⏹",
  Record: "⏺",
  Eject: "⏏",
  Cinema: "🎦",
  Dim: "🔅",
  Bright: "🔆",
  "Network antenna bars": "📶",
  "Vibration mode": "📳",
  "Mobile phone off": "📴",
  Female: "♀",
  Male: "♂",
  Transgender: "⚧",
  Times: "✖",
  Plus: "➕",
  Minus: "➖",
  Divide: "➗",
  Equals: "🟰",
  Infinity: "♾",
  "Double exclamation": "‼",
  "Exclamation and question mark": "⁉",
  "Red question mark": "❓",
  "White question mark": "❔",
  "Red exclamation mark": "❗",
  "White exclamation mark": "❕",
  "Wavy dash": "〰",
  "Currency exchange": "💱",
  "Heavy green dollar sign": "💲",
  "Medical symbol": "⚕",
  "Recycling symbol": "♻",
  "Fleur-de-lis": "⚜",
  Trident: "🔱",
  "Name badge": "📛",
  "Japanese symbol for beginner": "🔰",
  "Hollow red circle": "⭕",
  "Green box with checkmark": "✅",
  "Blue box with checkmark": "☑",
  Checkmark: "✔",
  Crossmark: "❌",
  "Green crossmark": "❎",
  "Curly loop": "➰",
  "Double curly loop": "➿",
  "PArt alternation mark": "〽",
  "Eight-spoked asterik": "✳",
  "Eight-pointed star": "✴",
  Sparkle: "❇",
  "Copyright symbol": "©",
  Registered: "®",
  Trademark: "™",
  "# Keycap": "#️⃣",
  "* Keycap": "*️⃣",
  "0 Keycap": "0️⃣",
  "1 Keycap": "1️⃣",
  "2 Keycap": "2️⃣",
  "3 Keycap": "3️⃣",
  "4 Keycap": "4️⃣",
  "5 Keycap": "5️⃣",
  "6 Keycap": "6️⃣",
  "7 Keycap": "7️⃣",
  "8 Keycap": "8️⃣",
  "9 Keycap": "9️⃣",
  "10 Keycap": "🔟",
  "Input Latin uppercase": "🔠",
  "Input Latin lowercase": "🔡",
  "Input numbers": "🔢",
  "Input symbols": "🔣",
  "Input Latin letters": "🔤",
  "A blood type": "🅰",
  "AB blood type": "🆎",
  "B blood type": "🅱",
  "O blood type": "🅾",
  "CL button": "🆑",
  "Cool button": "🆒",
  "Free button": "🆓",
  "Info button": "ℹ",
  "ID button": "🆔",
  "Circled M": "Ⓜ",
  "New button": "🆕",
  "NG button": "🆖",
  "OK button": "🆗",
  "P button": "🅿",
  "SOS button": "🆘",
  "UP! button": "🆙",
  "VS Button": "🆚",
  "Red circle": "🔴",
  "Orange circle": "🟠",
  "Yellow circle": "🟡",
  "Green circle": "🟢",
  "Blue circle": "🔵",
  "Purple circle": "🟣",
  "Brown circle": "🟤",
  "Black circle": "⚫",
  "White circle": "⚪",
  "Red square": "🟥",
  "Orange square": "🟧",
  "Yellow square": "🟨",
  "Green square": "🟩",
  "Blue square": "🟦",
  "Purple square": "🟪",
  "Brown square": "🟫",
  "Black square": "⬛",
  "White square": "⬜",
  "Large orange diamond": "🔶",
  "Large blue diamond": "🔷",
  "Small orange diamond": "🔸",
  "Small blue diamond": "🔹",
  "Red triangle pointed up": "🔺",
  "Red triangle pointed down": "🔻",
  "Diamond with a dot": "💠",
  "Radio button": "🔘",
  "White square button": "🔳",
  "Black square button": "🔲",
  "Chequered flag": "🏁",
  "Triangular flag": "🚩",
  "Crossed flag": "🎌",
  "Black flag": "🏴",
  "White flag": "🏳",
  "Rainbow flag": "🏳️‍🌈",
  "Transgender flag": "🏳️‍⚧️",
  "Pirate flag": "🏴‍☠️",
  "Ascension Island flag": "🇦🇨",
  "Andorra flag": "🇦🇩",
  "UAE flag": "🇦🇪",
  "Afghanistan flag": "🇦🇫",
  "Antigua and Berbuda flag": "🇦🇬",
  "Anguila flag": "🇦🇮",
  "Albania flag": "🇦🇱",
  "Armenia flag": "🇦🇲",
  "Angola flag": "🇦🇴",
  "Antarctica flag": "🇦🇶",
  "Argentina flag": "🇦🇷",
  "American Samoa flag": "🇦🇸",
  "Austria flag": "🇦🇹",
  "Australia flag": "🇦🇺",
  "Aruba flag": "🇦🇼",
  "Åland Islands flag": "🇦🇽",
  "Azerbaijan flag": "🇦🇿",
  "Bosnia flag": "🇧🇦",
  "Barbados flag": "🇧🇧",
  "Bangladesh flag": "🇧🇩",
  "Belgium flag": "🇧🇪",
  "Burkina Faso flag": "🇧🇫",
  "Bulgaria flag": "🇧🇬",
  "Bahrain flag": "🇧🇭",
  "Burundi flag": "🇧🇮",
  "Benin Republic flag": "🇧🇯",
  "St. Barthélemy": "🇧🇱",
  "Bermuda flag": "🇧🇲",
  "Brunei flag": "🇧🇳",
  "Bolivia flag": "🇧🇴",
  "Caribbean Netherlands flag": "🇧🇶",
  "Brazil flag": "🇧🇷",
  "Bahamas flag": "🇧🇸",
  "Bhutan flag": "🇧🇹",
  "Bouvet Island flag": "🇧🇻",
  "Botswana flag": "🇧🇼",
  "Belarus flag": "🇧🇾",
  "Belize flag": "🇧🇿",
  "Canada flag": "🇨🇦",
  "Cocos Islands flag": "🇨🇨",
  "Congo DR flag": "🇨🇩",
  "CAR (Central African Republic) flag": "🇨🇫",
  "Congo Brazzaville flag": "🇨🇬",
  "Switzerland flag": "🇨🇭",
  "Côte d’Ivoire flag": "🇨🇮",
  "Cook Islands flag": "🇨🇰",
  "Chile flag": "🇨🇱",
  "Cameroun flag": "🇨🇲",
  "China flag": "🇨🇳",
  "Columbia flag": "🇨🇴",
  "Clipperton Island flag": "🇨🇵",
  "Costa Rica flag": "🇨🇷",
  "Cuba flag": "🇨🇺",
  "Cape Verde Island flag": "🇨🇻",
  "Curaçao flag": "🇨🇼",
  "Christmas Island flag": "🇨🇽",
  "Cyprus flag": "🇨🇾",
  "Germany flag": "🇩🇪",
  "Diego Garcia flag": "🇩🇬",
  "Djibouti flag": "🇩🇯",
  "Denmark flag": "🇩🇰",
  "Dominica flag": "🇩🇲",
  "Dominican Republic flag": "🇩🇴",
  "Algeria flag": "🇩🇿",
  "Ceuta & Melilla flag": "🇪🇦",
  "Ecuador flag": "🇪🇨",
  Estonia: "🇪🇪",
  "Egypt flag": "🇪🇬",
  "Western Sahara flag": "🇪🇭",
  "Eritrea flag": "🇪🇷",
  "Spain flag": "🇪🇸",
  "Ethiopia flag": "🇪🇹",
  "EU flag": "🇪🇺",
  "Finland flag": "🇫🇮",
  "Fiji flag": "🇫🇯",
  "Falkland Island flag": "🇫🇰",
  "Micronesia flag": "🇫🇲",
  "Faroe Island flag": "🇫🇴",
  "France flag": "🇫🇷",
  "Gabon flag": "🇬🇦",
  "United Kingdom flag": "🇬🇧",
  "Grenada flag": "🇬🇩",
  "Georgia flag": "🇬🇪",
  "French Guiana flag": "🇬🇫",
  "Guernsey flag": "🇬🇬",
  "Ghana flag": "🇬🇭",
  "Gibraltar flag": "🇬🇮",
  "Greenland flag": "🇬🇱",
  "Gambia flag": "🇬🇲",
  "Guinea flag": "🇬🇳",
  "Guadeloupe flag": "🇬🇵",
  "Equitorial Guinea flag": "🇬🇶",
  "Greece flag": "🇬🇷",
  "South Georgia & South Sandwich Islands flag": "🇬🇸",
  "Guatemala flag": "🇬🇹",
  "Guinea Bissau flag": "🇬🇼",
  "Guyana flag": "🇬🇾",
  "Hong Kong flag": "🇭🇰",
  "Heard & McDonald Islands flag": "🇭🇲",
  "Honduras flag": "🇭🇳",
  "Croatia flag": "🇭🇷",
  "Haiti flag": "🇭🇹",
  "Hungary flag": "🇭🇺",
  "Canary Islands flag": "🇮🇨",
  "Indonesia flag": "🇮🇩",
  "Island flag": "🇮🇪",
  "Israel flag": "🇮🇱",
  "Isle of Man flag": "🇮🇲",
  "India flag": "🇮🇳",
  "British Indian Ocean Territory flag": "🇮🇴",
  "Iraq flag": "🇮🇶",
  "Iran flag": "🇮🇷",
  "Iceland flag": "🇮🇸",
  "Italy flag": "🇮🇹",
  "Jersey flag": "🇯🇪",
  "Jamaica flag": "🇯🇲",
  "Jordan flag": "🇯🇴",
  "Japan flag": "🇯🇵",
  "Kenya flag": "🇰🇪",
  "Kyrgyzstan flag": "🇰🇬",
  "": "🇰🇭",
  "Cambodia flag": "🇰🇭",
  "Kiribati flag": "🇰🇮",
  "Comoros Island flag": "🇰🇲",
  "St. Kitts & Nevis Flag": "🇰🇳",
  "North Korea flag": "🇰🇵",
  "South Korea flag": "🇰🇷",
  "Kuwait flag": "🇰🇼",
  "Cayman Island flag": "🇰🇾",
  "Kazakhstan flag": "🇰🇿",
  "Laos flag": "🇱🇦",
  "Lebanon flag": "🇱🇧",
  "St. Lucia flag": "🇱🇨",
  "Liechtenstein flag": "🇱🇮",
  "Sri Lanka flag": "🇱🇰",
  "Liberia flag": "🇱🇷",
  "Lesotho flag": "🇱🇸",
  "LIthuania flag": "🇱🇹",
  "Latvia flag": "🇱🇻",
  "Libya flag": "🇱🇾",
  "Morocco flag": "🇲🇦",
  "Monaco flag": "🇲🇨",
  "Moldova flag": "🇲🇩",
  "Montenegro flag": "🇲🇬",
  "Marshall Islands flag": "🇲🇭",
  "North Macedonia flag": "🇲🇰",
  "Mali flag": "🇲🇱",
  "Myanmar flag": "🇲🇲",
  "Mongolia flag": "🇲🇳",
  "Macao flag": "🇲🇴",
  "Northern Mariana Islands flag": "🇲🇵",
  "Marthinique flag": "🇲🇶",
  "Mauritania flag": "🇲🇷",
  "Montserrat flag": "🇲🇸",
  "Malta flag": "🇲🇹",
  "Mauritius flag": "🇲🇺",
  "Maldives flag": "🇲🇻",
  "Malawi flag": "🇲🇼",
  "Mexico flag": "🇲🇽",
  "Malaysia flag": "🇲🇾",
  "Mozambique flag": "🇲🇿",
  "Namibia flag": "🇳🇦",
  "New Caledonia flag": "🇳🇨",
  "Niger flag": "🇳🇪",
  "Norfolk Island flag": "🇳🇫",
  "Nigeria flag": "🇳🇬",
  "Nicaragua flag": "🇳🇮",
  "Netherlands flag": "🇳🇱",
  "Norway flag": "🇳🇴",
  "Nepal flag": "🇳🇵",
  "Nauru flag": "🇳🇷",
  "Niue flag": "🇳🇺",
  "New Zealand flag": "🇳🇿",
  "Oman flag": "🇴🇲",
  "Panama flag": "🇵🇦",
  "Peru flag": "🇵🇪",
  "French Polynesia flag": "🇵🇫",
  "Papua New Guinea flag": "🇵🇬",
  "Philipines flag": "🇵🇭",
  "Pakistan flag": "🇵🇰",
  "Poland flag": "🇵🇱",
  "St. Pierre & Miquelon": "🇵🇲",
  "Pitcairn Islands flag": "🇵🇳",
  "Puerto Rico flag": "🇵🇷",
  "Palestinian Territories flag": "🇵🇸",
  "Portugal flag": "🇵🇹",
  "Palau flag": "🇵🇼",
  "Paraguay flag": "🇵🇾",
  "Qatar flag": "🇶🇦",
  "Réunion flag": "🇷🇪",
  "Serbia flag": "🇷🇸",
  "Russia flag": "🇷🇺",
  "Rwanda flag": "🇷🇼",
  "Saudi Arabia flag": "🇸🇦",
  "Solomon Islands": "🇸🇧",
  "Seychelles flag": "🇸🇨",
  "Sudan flag": "🇸🇩",
  "Sweeden flag": "🇸🇪",
  "Singapore flag": "🇸🇬",
  "St. Helena flag": "🇸🇭",
  "Slovenia flag": "🇸🇮",
  "Svalbard & Jan Mayen": "🇸🇯",
  "Slovakia flag": "🇸🇰",
  "Sierra Leone flag": "🇸🇱",
  "San Marino flag": "🇸🇲",
  "Senegal flag": "🇸🇳",
  "Somalia flag": "🇸🇴",
  "Suriname flag": "🇸🇷",
  "South Sudan flag": "🇸🇸",
  "São Tomé & Príncipe flag": "🇸🇹",
  "El Salvador flag": "🇸🇻",
  "Saint Maarten flag": "🇸🇽",
  "Syria flag": "🇸🇾",
  "Eswatini (Swaziland) flag": "🇸🇿",
  "Tristan da Cunha flag": "🇹🇦",
  "Turks & Caicos Islands flag": "🇹🇨",
  "Chad flag": "🇹🇩",
  "French Southern Territories flag": "🇹🇫",
  "Togo flag": "🇹🇬",
  "Thailand flag": "🇹🇭",
  "Tajikistan flag": "🇹🇯",
  "Tokelau flag": "🇹🇰",
  "Timor-Leste flag": "🇹🇱",
  "Turkmenistan flag": "🇹🇲",
  "Tunisia flag": "🇹🇳",
  "Tonga flag": "🇹🇴",
  "Turkey flag": "🇹🇷",
  "Trinidad and Tobago flag": "🇹🇹",
  "Tuvalu flag": "🇹🇻",
  "Taiwan flag": "🇹🇼",
  "Tanzania flag": "🇹🇿",
  "Ukraine flag": "🇺🇦",
  "Uganda flag": "🇺🇬",
  "US Outlying Islands flag": "🇺🇲",
  "United Nations (UN) flag": "🇺🇳",
  "United State flag": "🇺🇸",
  "Uruguay flag": "🇺🇾",
  "Uzbekistan flag": "🇺🇿",
  "Vatical City flag": "🇻🇦",
  "St. Vincent & Grenadines flag": "🇻🇨",
  "Venezuela flag": "🇻🇪",
  "British Virgin Islands flag": "🇻🇬",
  "U.S. Virgin Islands": "🇻🇮",
  "Vietnam flag": "🇻🇮",
  "Vanuatu flag": "🇻🇺",
  "Wallis & Futuna flag": "🇼🇫",
  "Samoa flag": "🇼🇸",
  "Kosovo flag": "🇽🇰",
  "Yemen flag": "🇾🇪",
  "Mayotte flag": "🇾🇹",
  "South Africa flag": "🇿🇦",
  "Zambia flag": "🇿🇲",
  "Zimbabwe flag": "🇿🇼",
  "England flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Scotland flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Wales flag": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};
